wiki/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib.syndication.views import feed
from wiki.feeds import LatestEdits
import views # relative import

feeds = {
    'latest': LatestEdits
}

urlpatterns = patterns('',
    (r'^$', views.view_page, {'slug': 'index'}),
    (r'^r/$', views.redirecter),
    (r'^latest-changes/$', views.latest_changes),
    (r'^(\w{1,30})/$', views.view_page),
    (r'^(\w{1,30})/edit/$', views.edit_page),
    (r'^(\w{1,30})/history/$', views.history),
    (r'^(\w{1,30})/history/(\d{1,6})/$', views.view_version),
    (r'^(\w{1,30})/history/(\d{1,6})/diff/$', views.previous_version_diff),
    (r'^feeds/(?P<url>.*)/$', feed, {'feed_dict': feeds}),
)

wiki/models.py
from django.db import models
import re
from google.appengine.ext import db

class PageManager(models.Manager):
    def create_with_auto_version(self, slug, headline, content, change_message, change_ip, minor_edit):
        """
        Creates and returns a Page object with the given attributes.
        Automatically sets version to the next available version number for
        the given slug, in a way that avoids race conditions.
        """
        try:
            latest_page = Page.objects.order_by('-version').filter('slug =', slug)[0]
            version = latest_page.version + 1
        except IndexError:
            version = 1
        s = Page.get_or_insert("page%s%s" % (slug, version), slug=slug, headline=headline, content=content, change_message=change_message,
        	change_ip=change_ip, minor_edit=minor_edit, version=version)
        s.put()        
        return s

    def order_by(self, sort_order):
    	return db.Query(Page).order(sort_order)

class Page(db.Model):
    slug = db.StringProperty()
    headline = db.StringProperty()
    content = db.TextProperty()
    version = db.IntegerProperty()
    change_date = db.DateTimeProperty(auto_now_add=True)
    change_message = db.StringProperty()
    change_user = db.UserProperty(auto_current_user_add=True)
    change_ip = db.StringProperty()
    minor_edit = db.BooleanProperty()
    objects = PageManager()

    def __unicode__(self):
        return self.slug

    def url(self):
        return '/%s/' % self.slug

    def edit_url(self):
        return '/%s/edit/' % self.slug

    def history_url(self):
        return '/%s/history/' % self.slug

    def version_url(self):
        return '/%s/history/%s/' % (self.slug, self.version)

    def diff_url(self):
        return '/%s/history/%s/diff/' % (self.slug, self.version)

wiki/views.py
from django import forms
from django.core.paginator import Paginator, EmptyPage
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render_to_response
from ragendja.dbutils import get_object_or_404
from wiki.models import Page
from difflib import unified_diff
import urllib
import logging

easy_diff = lambda x, y: '\n'.join(unified_diff(x.split('\n'), y.split('\n'), 'Old page', 'New page', lineterm=""))

class PageForm(forms.Form):
    headline = forms.CharField(max_length=80, widget=forms.TextInput(attrs={'size': 80}))
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 20, 'cols': 70}))
    change_message = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'size': 100}))
    minor_edit = forms.BooleanField(widget=forms.CheckboxInput, required=False)
    version = forms.IntegerField(widget=forms.HiddenInput)

def redirecter(request):
    "Redirects to a given URL without sending the 'Referer' header."
    try:
        url = request.GET['url']
    except KeyError:
        raise Http404
    if not url.startswith('http://') and not url.startswith('https://'):
        raise Http404
    return HttpResponse('<html><head><meta http-equiv="Refresh" content="0; URL=%s"></head><body>Redirecting...</body></html>' % urllib.unquote_plus(url))

def view_page(request, slug):
    try:
        page = Page.objects.order_by('-version').filter('slug =', slug)[0]
    except IndexError:
        page = Page(slug=slug) # Temporarily construct Page object so we can call edit_url()
        return HttpResponseRedirect(page.edit_url())
    return render_to_response('wiki/view_page.html', {'page': page})

def view_version(request, slug, version):
    page = get_object_or_404(Page, key_name="page%s%s" % (slug, version))
    return render_to_response('wiki/view_version.html', {'page': page})

def edit_page(request, slug):
    try:
        latest_page = Page.objects.order_by('-version').filter('slug =', slug)[0]
    except IndexError:
        latest_page = None
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if latest_page:
                if latest_page.headline == cd['headline'] and latest_page.content == cd['content']:
                    # If no changes were made, don't touch the database.
                    return HttpResponseRedirect(latest_page.url())
                if latest_page.version != int(cd['version']):
                    diff = easy_diff(Page.objects.get(slug=slug, version=cd['version']).content, cd['content'])
                    return render_to_response('wiki/edit_conflict.html', {'diff': diff, 'latest_page': latest_page})
            new_page = Page.objects.create_with_auto_version(slug, cd['headline'], cd['content'],
                cd['change_message'], request.META['REMOTE_ADDR'], cd['minor_edit'])
            return HttpResponseRedirect(new_page.url())
    else:
        if latest_page is not None:
            form = PageForm({'headline': latest_page.headline, 'content': latest_page.content, 'version': latest_page.version})
        else:
            form = PageForm(initial={'change_message': 'Created page', 'version': 0})
    return render_to_response('wiki/edit_page.html', {'old_page': latest_page, 'slug': slug, 'form': form})

def history(request, slug):
    page_list = Page.objects.order_by('-version').filter('slug =', slug)
    if not page_list:
        raise Http404("A history doesn't exist for the given slug.")
    return render_to_response('wiki/history.html', {'page_list': page_list, 'slug': slug})

def version_diff(request, slug, version1, version2):
    if int(version1) == 0:
        old_content = ''
    else:
        old_content = get_object_or_404(Page, key_name="page%s%s" % (slug, version1)).content
    page = get_object_or_404(Page, key_name="page%s%s" % (slug, version2))
    diff = easy_diff(old_content, page.content)
    return render_to_response('wiki/version_diff.html', {'diff': diff, 'slug': slug, 'version1': version1, 'version2': version2, 'page': page})

def previous_version_diff(request, slug, version):
    return version_diff(request, slug, int(version)-1, version)

def latest_changes(request):
    p = Paginator(Page.objects.order_by('-change_date'), 30)
    try:
        page_num = int(request.GET.get('p', '1'))
    except ValueError:
        page_num = 1
    try:
        page = p.page(page_num)
    except EmptyPage:
        raise Http404('Invalid page')
    return render_to_response('wiki/latest_changes.html', {'result_page': page})

templates/wiki/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
	<title>{% block title %}{% endblock %} | Wiki</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=320; initial-scale=.75; maximum-scale=.75; user-scalable=0;">
	<link rel="alternate" type="application/atom+xml" href="/feeds/latest/" title="Latest wiki edits">
	<link rel="stylesheet" href="/styles/wiki.css" type="text/css" media="all">
	{% block extrahead %}{% endblock %}
</head>
<body>
	{% block header %}
	<div id="header">
		<a id="site-title" href="/">Wiki</a>
		<ul id="site-nav">
			<li><a href="/feeds/latest/">Data feeds</a></li>
			<li><a href="/latest-changes/">Latest changes</a></li>
		</ul>
	</div>
	{% endblock %}

	<div id="content">
		{% block content %}{% endblock %}
	</div><!--/content-->

	{% block footer %}{% endblock %}
</body>
</html>

templates/wiki/data/city.html
{% extends "wiki/base.html" %}

{% load wiki %}

{% block title %}{{ city.name }} data feeds{% endblock %}

{% block content %}

<h1><a href="../../">Data feeds</a> / {{ city.name }}</h1>

<table>
    <thead>
        <tr>
            <th>Data type</th>
            <th>PP status</th>
            <th>Tech status</th>
            <th>Next step</th>
        </tr>
    </thead>
    <tbody>
        {% for data_source in data_source_list %}
        <tr{% if data_source.is_na %} style="background: #eee;"{% endif %}>
            <th><a href="{{ data_source.url }}">{{ data_source.data_type.name }}</a></th>
            <td>{{ data_source.get_pp_status_display }}</td>
            <td>{{ data_source.get_tech_status_display }}</td>
            <td>{{ data_source.next_step|markdown|safe }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/wiki/data/homepage.html
{% extends "wiki/base.html" %}

{% block title %}Data feeds{% endblock %}

{% block content %}

<h1>Data feeds</h1>

<p><a href="add_city/">Add a city</a> | <a href="add_type/">Add a type</a> | <a href="pp_status/">PP status</a> | <a href="tech_status/">Tech status</a> | <a href="maintenance/">Maintenance</a></p>

<table>
    <thead>
        <tr>
            <th>DATA</th>
            {% for city in city_list %}
            <th><a href="{{ city.url }}">{{ city.name }}</a></th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for type in type_list %}
        <tr>
            <th>{{ type.name }}</th>
            {% for source in type.source_list %}
                {% if source.id %}
                    <td><a href="{{ source.url }}">PP: {{ source.get_pp_status_display }}<br>Tech: {{ source.get_tech_status_display }}</a>
                {% else %}
                    <td style="background: #eee;"><a href="{{ source.url }}"><b>Unknown</b></a></td>
                {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/wiki/data/maintenance.html
{% extends "wiki/base.html" %}

{% block title %}Data feed maintenance{% endblock %}

{% block content %}

<h1><a href="../">Data feeds</a> / Maintenance</h1>

<table>
    <thead>
        <tr>
            <th>City</th>
            <th>Data type</th>
            <th>Maintenance needs</th>
        </tr>
    </thead>
    <tbody>
        {% for source in source_list %}
        <tr>
            <td>{% ifchanged %}<a href="{{ source.city.url }}">{{ source.city.name }}</a>{% endifchanged %}</td>
            <td><a href="{{ source.url }}">{{ source.data_type.name }}</a> (<a href="{{ source.edit_url }}">Edit</a>)</td>
            <td>{{ source.maintenance_needs }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/wiki/data/pp_status.html
{% extends "wiki/base.html" %}

{% block title %}People person status for data feeds{% endblock %}

{% block content %}

<h1><a href="../">Data feeds</a> / People person status</h1>

<img src="http://farm2.static.flickr.com/1378/1010524757_22efe161d2_m.jpg" align="right" />

<p>See also: <a href="../tech_status/">Tech status</a>
<table>
    <thead>
        <tr>
            <th>PP status</th>
            <th>City</th>
            <th>Data type</th>
        </tr>
    </thead>
    <tbody>
        {% for source in source_list %}
        <tr{% if source.is_na %} style="background: #eee;"{% endif %}>
            <td>{% ifchanged %}<strong>{{ source.get_pp_status_display }}</strong>{% endifchanged %}</td>
            <td><a href="{{ source.city.url }}">{{ source.city.name }}</a></td>
            <td><a href="{{ source.url }}">{{ source.data_type.name }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/wiki/data/source.html
{% extends "wiki/base.html" %}

{% load wiki %}

{% block title %}{{ source.data_type.name }} in {{ source.city.name }}{% endblock %}

{% block content %}

<h1><a href="../../../">Data feeds</a> / <a href="{{ source.city.url }}">{{ source.city.name }}</a> / {{ source.data_type.name }}</h1>

<table>
<tr><th>PP status</th><td><a href="../../../pp_status/">{{ source.get_pp_status_display }}</a></td></tr>
<tr><th>Tech status</th><td><a href="../../../tech_status/">{{ source.get_tech_status_display }}</a></td></tr>
<tr><th>Web site</th><td>{% if source.web_site %}<a href="/r/?url={{ source.web_site|urlencode }}">{{ source.web_site }}</a>{% else %}None{% endif %}</td></tr>
<tr><th>Contact name</th><td>{% if source.contact_name %}{{ source.contact_name }}{% else %}None{% endif %}</td></tr>
<tr><th>Contact phone</th><td>{% if source.contact_phone %}{{ source.contact_phone }}{% else %}None{% endif %}</td></tr>
<tr><th>Contact e-mail</th><td>{% if source.contact_email %}{{ source.contact_email }}{% else %}None{% endif %}</td></tr>
</table>

{% if source.next_step %}<h2>Next step</h2>{{ source.next_step|markdown|safe }}{% endif %}
{% if source.notes %}<h2>Notes</h2>{{ source.notes|markdown|safe }}{% endif %}
{% if source.fields_to_include %}<h2>Fields to include</h2>{{ source.fields_to_include|markdown|safe }}{% endif %}
{% if source.newsitem_headline_template %}<h2>Headline for newsitem_detail</h2>{{ source.newsitem_headline_template|markdown|safe }}{% endif %}
{% if source.summary_text_newsitem_detail %}<h2>Summary for newsitem_detail</h2>{{ source.summary_text_newsitem_detail|markdown|safe }}{% endif %}
{% if source.schema_description %}<h2>Schema description</h2>{{ source.schema_description|markdown|safe }}{% endif %}

{% endblock %}

{% block footer %}
<div id="footer">
	<p class="page-tools">
		<a class="button default" href="{{ source.edit_url }}">Edit</a>
	</p>
</div><!--/footer-->
{% endblock %}

templates/wiki/data/source_form.html
{% extends "wiki/base.html" %}

{% block title %}Update data source: {{ data_type.name }} in {{ city.name }}{% endblock %}

{% block extrahead %}
<style type="text/css">
#id_contact_name { width: 400px; }
#id_contact_email { width: 300px; }
#id_web_site { width: 600px; }
#id_next_step, #id_notes, #id_maintenance_needs, #id_fields_to_include,
#id_newsitem_headline_template, #id_summary_text_newsitem_detail, #id_schema_description { width: 600px; height: 300px; }
</style>
{% endblock %}

{% block content %}

<h1>Update: {{ data_type.name }} in {{ city.name }}</h1>

<form action="" method="post">
	<table>
		{{ form.as_table }}
		<tr class="submit-row"><th>&nbsp;</th><td><input class="button default" type="submit" value="Submit" /></td></tr>
	</table>
</form>

{% endblock %}

templates/wiki/data/tech_status.html
{% extends "wiki/base.html" %}

{% block title %}Tech status for data feeds{% endblock %}

{% block content %}

<h1><a href="../">Data feeds</a> / Tech status</h1>

<img src="http://farm2.static.flickr.com/1186/1010517495_7f54007d34_m.jpg" align="right" />

<p>See also: <a href="../pp_status/">People person status</a>
<table>
    <thead>
        <tr>
            <th>Tech status</th>
            <th>City</th>
            <th>Data type</th>
        </tr>
    </thead>
    <tbody>
        {% for source in source_list %}
        <tr{% if source.is_na %} style="background: #eee;"{% endif %}>
            <td>{% ifchanged %}<strong>{{ source.get_tech_status_display }}</strong>{% endifchanged %}</td>
            <td><a href="{{ source.city.url }}">{{ source.city.name }}</a></td>
            <td><a href="{{ source.url }}">{{ source.data_type.name }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/wiki/edit_conflict.html
{% extends "wiki/base.html" %}

{% block title %}Conflict!{% endblock %}

{% block content %}

<h1>Conflict!</h1>

<p>Somebody has saved changes to the <strong>{{ latest_page.slug }}</strong> page since the moment you clicked "Edit this page."</p>

<p><a href="{{ latest_page.edit_url }}">Go to this page</a>, then make your changes again. For your convenience, here's a diff of the changes you were about to save:</p>

<pre>
{{ diff }}
</pre>

{% endblock %}

templates/wiki/edit_page.html
{% extends "wiki/base.html" %}

{% block title %}{% if old_page %}Edit {{ old_page.slug }}{% else %}Create {{ slug }}{% endif %}{% endblock %}

{% block extrahead %}
<style type="text/css" media="screen">
	th label { display: block; padding: 0.6em 0; white-space: nowrap; }
	#id_content { line-height: 1.6em; }
	#id_headline,
	#id_content,
	#id_change_message { width: 98%; color: #222; font: 1em Arial, sans-serif; padding: 0.6em 9px; border: 1px solid #ccc; }
	#id_headline { font-weight: bold; }
</style>
{% endblock %}

{% block content %}

{% if old_page %}
<h1>Edit <a href="{{ old_page.url }}">{{ old_page.slug }}</a></h1>
{% else %}
<h1>Create {{ slug }}</h1>
{% endif %}

<form action="" method="post">
	<table>
		{{ form.as_table }}
		<tr class="submit-row"><th>&nbsp;</th><td><input class="button default" type="submit" value="Submit" /></td></tr>
	</table>
</form>

<h3>Markdown key</h3>
<table>
	<tr><td><code>[Link to URL](http://www.example.com/)</code></td><td><a href="http://www.example.com/">Link to URL</a></td></tr>
	<tr><td><code>[Link to wiki page](hello)</code></td><td><a href="/hello/">Link to wiki page</a></td></tr>
</table>
{% endblock %}

templates/wiki/feeds/latest_description.html
<dl>
    <dt>Summary</dt>
    <dd>
        {% if obj.change_message %}
        {{ obj.change_message|escape }}
        {% else %}
        <i>No summary given.</i>
        {% endif %}
    </dd>

    <dt>Version</dt>
    <dd>
        <a href="{{ obj.version_url }}">{{ obj.version }}</a>
        (<a href="{{ obj.diff_url }}">Changes</a>)
    </dd>
</dl>

templates/wiki/feeds/latest_title.html
{{ obj.headline|escape }}

templates/wiki/generic_form.html
{% extends "wiki/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<h1>{{ title }}</h1>

<form action="" method="post">
	<table>
		{{ form.as_table }}
		<tr class="submit-row"><th>&nbsp;</th><td><input class="button default" type="submit" value="Submit" /></td></tr>
	</table>
</form>

{% endblock %}

templates/wiki/history.html
{% extends "wiki/base.html" %}

{% block title %}History for {{ slug }}{% endblock %}

{% block content %}

<h1>History for <a href="{{ page_list.0.url }}">{{ slug }}</a></h1>

<table class="history">
	<thead>
		<tr>
			<th>Revision</th>
			<th>Date</th>
			<th>User</th>
			<th>Message</th>
		</tr>
	</thead>
	<tbody>
	{% for page in page_list %}
		<tr>
			<td class="revision"><a class="version button default" href="{{ page.version_url }}">{{ page.version }}</a> <a class="diff button" href="{{ page.diff_url }}">Changes</a></td>			
			<td class="date">{{ page.change_date|date:"F j, Y, P" }}</td>
			<td class="user">{{ page.change_user }}</td>
			<td class="message">{{ page.change_message|escape }}</td>
		</tr>
	{% endfor %}
	</tbody>
</table>

{% endblock %}

templates/wiki/latest_changes.html
{% extends "wiki/base.html" %}

{% block title %}Latest changes{% endblock %}

{% block content %}

<h1>Latest changes</h1>

<p>{% if result_page.has_previous %}<a href="?p={{ result_page.previous_page_number }}">Previous</a>{% else %}Previous{% endif %} | {% if result_page.has_next %}<a href="?p={{ result_page.next_page_number }}">Next</a>{% else %}Next{% endif %}</p>

<table class="history latest-changes">
	<thead>
		<tr>
			<th>Page</th>
			<th>Revision</th>
		</tr>
	</thead>
	<tbody>
	{% for page in result_page.object_list %}
		<tr>
			<td class="page">
				<a href="{{ page.url }}">{{ page.headline }}</a>
			</td>
			<td class="revision">
				<a class="version button default" href="{{ page.version_url }}">{{ page.version }}</a> <a class="diff button" href="{{ page.diff_url }}">Changes</a>
				<p class="info">Updated by <span class="user">{{ page.change_user }}</span> <span class="time">{% if page.change_date|timesince %}{{ page.change_date|timesince }} ago{% else %}just now{% endif %}</span></p>
				<p class="message">{{ page.change_message|escape }}</p>
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>

<p>{% if result_page.has_previous %}<a href="?p={{ result_page.previous_page_number }}">Previous</a>{% else %}Previous{% endif %} | {% if result_page.has_next %}<a href="?p={{ result_page.next_page_number }}">Next</a>{% else %}Next{% endif %}</p>

{% endblock %}

templates/wiki/list_orphans.html
{% extends "wiki/base.html" %}

{% block title %}Orphaned pages{% endblock %}

{% block content %}

<h1>Orphaned pages</h1>

<ul>
{% for page in orphans %}
    <li>
        <a href="{{ page.url }}">{{ page.headline }}</a>
    </li>
{% endfor %}
</ul>

{% endblock %}

templates/wiki/search.html
{% extends "wiki/base.html" %}

{% load wiki %}

{% block title %}Search the wiki{% endblock %}

{% block content %}

<h1>Search the wiki</h1>

<form method="get">
<input type="text" name="query" value="{{ query|escape }}">
<input type="submit" value="Search">
</form>

{% if error %}
<p class="error">
There was an error:
<pre>{{ error }}</pre>
</p>
{% endif %}

{% if results %}
<p>Found {{ total }} result{{ total|pluralize }}.</p>
{% for page in results %}
<p><b><a href="{{ page.url }}">{{ page.headline }}</a></b>
</p>
<p>
{{ page.content|markdown|striptags|truncatewords:20 }}
</p>
{% endfor %}
{% endif %}

{% endblock %}

templates/wiki/version_diff.html
{% extends "wiki/base.html" %}

{% block title %}Changes between versions {{ version1 }} and {{ version2 }} of {{ slug }}{% endblock %}

{% block content %}
<h1>Changes between versions {{ version1 }} and {{ version2 }} of <a href="{{ page.url }}">{{ slug }}</a></h1>

<p class="page-tools">Changes were made by <span class="user">{{ page.change_user }}</span>.</p>

<div class="codeport">
	<pre>{{ diff|escape }}</pre>
</div>
{% endblock %}

{% block footer %}
<div id="footer">
	<p class="page-tools"><a class="button" href="{{ page.history_url }}">Other versions of this page</a> <a class="button default" href="{{ page.url }}">Current version</a></p>
</div>
{% endblock %}

templates/wiki/view_page.html
{% extends "wiki/base.html" %}

{% load wiki %}

{% block title %}{{ page.headline|escape }}{% endblock %}

{% block content %}

<h1>{{ page.headline|escape }}</h1>

{{ page.content|markdown|safe }}

{% endblock %}

{% block footer %}
<div id="footer">
	<p class="page-tools">
		<a class="button default" href="{{ page.edit_url }}">Edit</a>
		<a class="button" href="{{ page.history_url }}">View history</a>
		<span class="timestamp"><a href="{{ page.diff_url }}">Last updated</a> by <span class="user">{{ page.change_user }}</span> {% if page.change_date|timesince %}{{ page.change_date|timesince }} ago{% else %}just now{% endif %}.</span>
	</p>
</div><!--/footer-->
{% endblock %}

templates/wiki/view_version.html
{% extends "wiki/base.html" %}

{% load wiki %}

{% block title %}Version {{ page.version }} of {{ page.headline|escape }}{% endblock %}

{% block content %}

<h1>Version {{ page.version }} of {{ page.headline|escape }}</h1>

{{ page.content|markdown|safe }}

{% endblock %}

{% block footer %}
<div id="footer">
	<p class="page-tools"><a class="button" href="{{ page.history_url }}">Other versions of this page</a></p>
</div>
{% endblock %}